/*
=============================================================================

     File: C3_errors.c. Error codes and their meanings generated from 
           .\source-15\c3_errors.cpp
     Copyright Sadram, Inc., 2022. All rights reserved.

 Do not edit this file since it will be overwritten by BuildErrors.exe.
 =============================================================================
*/

enum {XSEVERITY_NOERROR, XSEVERITY_INFORMATION, XSEVERITY_HINT, XSEVERITY_WARNING, XSEVERITY_DANGEROUS, XSEVERITY_ERROR, XSEVERITY_TELL_USER, XSEVERITY_SYSTEM, XSEVERITY_CATASTROPHIC};
#define DLL "dll" 

